name: flutter_wifi_control
description: "Flutter wifi control plugin"
version: 0.0.1+1
homepage: "https://github.com/gerardggf/flutter_wifi_control"

environment:
  sdk: ^3.6.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_wifi_control
        pluginClass: FlutterWifiControlPlugin
      ios:
        pluginClass: FlutterWifiControlPlugin
